#!/system/bin/sh
######################################################################
###################### DreamNarae Pure 1.0 ###########################
#################################Best of DreamNarae Tweak#############
## Made by Sopiane(Dong Gil, Seo)
## and Rie (Eun Hee, Lee)
## and Iren (Jung Yeon, Lee)
## and Ayana (Eun Jung, Lee)
## With four people going to make the best Android Tweak!
## Supported by Colorful Harmony Team- Angeloid Team
## Thanks to Developer, and User.
## This Version is Final Version We made.
## Enjoy Your Device With DreamNarae!
######################################################################

echo "00cpu Start"

if [ -e /sys/devices/system/cpu/cpu0/cpufreq/deepsleep_cpulevel ]; then
    echo "4" > /sys/devices/system/cpu/cpu0/cpufreq/deepsleep_cpulevel
    echo "4" > /sys/devices/system/cpu/cpu0/cpufreq/deepsleep_cpulevel;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/cpu0/cpufreq/deepsleep_buslevel ]; then
    echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/deepsleep_buslevel
    echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/deepsleep_buslevel;
	echo "Activited!"
fi

if [ -e /sys/module/cpuidle/parameters/enable_mask ]; then
    echo "3" > /sys/module/cpuidle/parameters/enable_mask
    echo "3" > /sys/module/cpuidle/parameters/enable_mask;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/sched_mc_power_savings ]; then
    echo "1" > /sys/devices/system/cpu/sched_mc_power_savings
    echo "1" > /sys/devices/system/cpu/sched_mc_power_savings;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/sched_mc_power_savings ]; then
    echo "1" > /sys/devices/system/cpu/sched_mc_power_savings
    echo "1" > /sys/devices/system/cpu/sched_mc_power_savings;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/cpu0/cpufreq/smooth_target ]; then
	echo "2" > /sys/devices/system/cpu/cpu0/cpufreq/smooth_target
	echo "2" > /sys/devices/system/cpu/cpu0/cpufreq/smooth_target;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/cpu1/cpufreq/smooth_target ]; then
	echo "2" > /sys/devices/system/cpu/cpu1/cpufreq/smooth_target
	echo "2" > /sys/devices/system/cpu/cpu1/cpufreq/smooth_target;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/cpu2/cpufreq/smooth_target ]; then
	echo "2" > /sys/devices/system/cpu/cpu2/cpufreq/smooth_target
	echo "2" > /sys/devices/system/cpu/cpu2/cpufreq/smooth_target;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/cpu3/cpufreq/smooth_target ]; then
	echo "2" > /sys/devices/system/cpu/cpu3/cpufreq/smooth_target
	echo "2" > /sys/devices/system/cpu/cpu3/cpufreq/smooth_target;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/cpu0/cpufreq/smooth_offset ]; then
	echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/smooth_offset
	echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/smooth_offset;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/cpu1/cpufreq/smooth_offset ]; then
	echo "1" > /sys/devices/system/cpu/cpu1/cpufreq/smooth_offset
	echo "1" > /sys/devices/system/cpu/cpu1/cpufreq/smooth_offset;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/cpu2/cpufreq/smooth_offset ]; then
	echo "1" > /sys/devices/system/cpu/cpu2/cpufreq/smooth_offset
	echo "1" > /sys/devices/system/cpu/cpu2/cpufreq/smooth_offset;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/cpu3/cpufreq/smooth_offset ]; then
	echo "1" > /sys/devices/system/cpu/cpu3/cpufreq/smooth_offset
	echo "1" > /sys/devices/system/cpu/cpu3/cpufreq/smooth_offset;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/cpu0/cpufreq/smooth_step ]; then
	echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/smooth_step
	echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/smooth_step;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/cpu1/cpufreq/smooth_step ]; then
	echo "1" > /sys/devices/system/cpu/cpu1/cpufreq/smooth_step
	echo "1" > /sys/devices/system/cpu/cpu1/cpufreq/smooth_step;
	echo "Activited!"
fi

if [ -e /sys/devices/system/cpu/cpu2/cpufreq/smooth_step ]; then
	echo "1" > /sys/devices/system/cpu/cpu2/cpufreq/smooth_step
	echo "1" > /sys/devices/system/cpu/cpu2/cpufreq/smooth_step;
	echo "Activited!"
fi
if [ -e /sys/devices/system/cpu/cpu3/cpufreq/smooth_step ]; then
	echo "1" > /sys/devices/system/cpu/cpu3/cpufreq/smooth_step
	echo "1" > /sys/devices/system/cpu/cpu3/cpufreq/smooth_step;
	echo "Activited!"
fi

if [ -e /sys/devices/virtual/misc/second_core/hotplug_on ]; then
	echo "on" > /sys/devices/virtual/misc/second_core/hotplug_on
	echo "on" > /sys/devices/virtual/misc/second_core/hotplug_on;
	echo "Activited!"
fi

if [ -e /sys/module/pm_hotplug/parameters/loadl ]; then
	echo 25 > /sys/module/pm_hotplug/parameters/loadl
	echo 25 > /sys/module/pm_hotplug/parameters/loadl;
	echo "Activited!"
fi

if [ -e /sys/module/pm_hotplug/parameters/loadh ]; then
	echo 25 > /sys/module/pm_hotplug/parameters/loadh
	echo 25 > /sys/module/pm_hotplug/parameters/loadh;
	echo "Activited!"
fi

if [ -e /sys/module/pm_hotplug/parameters/loadl_scroff ]; then
	echo 25 > /sys/module/pm_hotplug/parameters/loadl_scroff
	echo 25 > /sys/module/pm_hotplug/parameters/loadl_scroff;
	echo "Activited!"
fi

if [ -e /sys/module/pm_hotplug/parameters/loadh_scroff ]; then
	echo 25 > /sys/module/pm_hotplug/parameters/loadh_scroff
	echo 25 > /sys/module/pm_hotplug/parameters/loadh_scroff;
	echo "Activited!"
fi

if [ -e /sys/module/pm_hotplug/parameters/freq_cpu1on ]; then
	echo 500000 > /sys/module/pm_hotplug/parameters/freq_cpu1on
	echo 500000 > /sys/module/pm_hotplug/parameters/freq_cpu1on;
	echo "Activited!"
fi

if [ -e /sys/module/pm_hotplug/parameters/rate ]; then
	echo 200 > /sys/module/pm_hotplug/parameters/rate
	echo 200 > /sys/module/pm_hotplug/parameters/rate;
	echo "Activited!"
fi

if [ -e /sys/module/pm_hotplug/parameters/rate_cpuon ]; then
	echo 400 > /sys/module/pm_hotplug/parameters/rate_cpuon
	echo 400 > /sys/module/pm_hotplug/parameters/rate_cpuon;
	echo "Activited!"
fi

if [ -e /sys/module/pm_hotplug/parameters/rate_scroff ]; then
	echo 800 > /sys/module/pm_hotplug/parameters/rate_scroff
	echo 800 > /sys/module/pm_hotplug/parameters/rate_scroff;
	echo "Activited!"
fi

if [ -e /proc/sys/vm/panic_on_oom ]; then
   echo 0 > /proc/sys/vm/panic_on_oom
   echo 0 > /proc/sys/vm/panic_on_oom;
   echo "Activited!"
fi

if [ -e /proc/sys/kernel/panic ]; then 
   echo 0 > /proc/sys/kernel/panic
   echo 0 > /proc/sys/kernel/panic;
   echo "Activited!"
fi

if [ -e /proc/sys/kernel/panic_on_oops ]; then 
   echo 0 > /proc/sys/kernel/panic_on_oops
   echo 0 > /proc/sys/kernel/panic_on_oops;
   echo "Activited!"
fi

if [ -e /proc/sys/kernel/hung_task_timeout_secs ]; then 
   echo 0 > /proc/sys/kernel/hung_task_timeout_secs
   echo 0 > /proc/sys/kernel/hung_task_timeout_secs;
   echo "Activited!"
fi

if [ -e /proc/sys/kernel/softlockup_panic ]; then 
   echo 0 > /proc/sys/kernel/softlockup_panic
   echo 0 > /proc/sys/kernel/softlockup_panic;
   echo "Activited!"
fi

echo "00cpu Complete! Next to 01Loosy"