#!/system/bin/sh
######################################################################
###################### DreamNarae Pure 1.0 ###########################
#################################Best of DreamNarae Tweak#############
## Made by Sopiane(Dong Gil, Seo)
## and Rie (Eun Hee, Lee)
## and Iren (Jung Yeon, Lee)
## and Ayana (Eun Jung, Lee)
## With four people going to make the best Android Tweak!
## Supported by Colorful Harmony Team- Angeloid Team
## Thanks to Developer, and User.
## This Version is Final Version We made.
## Enjoy Your Device With DreamNarae!
######################################################################

echo "02memory Start!"
if [ -e /proc/sys/vm/swappiness ]; then
    echo 50 > /proc/sys/vm/swappiness;
	echo 50 > /proc/sys/vm/swappiness
	echo "Activited!"
fi

if [ -e /proc/sys/vm/min_free_kbytes ]; then
    echo 3072 > /proc/sys/vm/min_free_kbytes;
	echo 3072 > /proc/sys/vm/min_free_kbytes
	echo "Activited!"
fi

if [ -e /proc/sys/vm/dirty_expire_centisecs ]; then
    echo 3072 > /proc/sys/vm/dirty_expire_centisecs;
	echo 3072 > /proc/sys/vm/dirty_expire_centisecs
	echo "Activited!"
fi

if [ -e /proc/sys/vm/dirty_expire_centisecs ]; then
    echo 3072 > /proc/sys/vm/dirty_expire_centisecs;
	echo 3072 > /proc/sys/vm/dirty_expire_centisecs
	echo "Activited!"
fi

if [ -e /proc/sys/vm/dirty_writeback_centisecs ]; then
    echo 1500 > /proc/sys/vm/dirty_writeback_centisecs;
	echo 1500 > /proc/sys/vm/dirty_writeback_centisecs
	echo "Activited!"
fi

if [ -e /proc/sys/vm/dirty_background_ratio ]; then
    echo 7 > /proc/sys/vm/dirty_background_ratio;
	echo 7 > /proc/sys/vm/dirty_background_ratio
	echo "Activited!"
fi

if [ -e /proc/sys/vm/dirty_ratio ]; then
    echo 30 > /proc/sys/vm/dirty_ratio;
	echo 30 > /proc/sys/vm/dirty_ratio
	echo "Activited!"
fi

if [ -e /proc/sys/vm/vfs_cache_pressure ]; then
    echo 50 > /proc/sys/vm/vfs_cache_pressure;
    echo 50 > /proc/sys/vm/vfs_cache_pressure
	echo "Activited!"
fi

if [ -e /proc/sys/vm/laptop_mode ]; then
    echo 0 > /proc/sys/vm/laptop_mode;
    echo 0 > /proc/sys/vm/laptop_mode
	echo "Activited!"
fi

if [ -e /proc/sys/vm/panic_on_oom ]; then
    echo 0 > /proc/sys/vm/panic_on_oom;
    echo 0 > /proc/sys/vm/panic_on_oom
	echo "Activited!"
fi

if [ -e /proc/sys/vm/page-cluster ]; then
    echo 3 > /proc/sys/vm/page-cluster;
    echo 3 > /proc/sys/vm/page-cluster
	echo "Activited!"
fi

if [ -e /proc/sys/kernel/sched_min_granularity_ns ]; then
    echo "1500000" > /proc/sys/kernel/sched_min_granularity_ns
    echo "1500000" > /proc/sys/kernel/sched_min_granularity_ns;
	echo "Activited!"
fi

if [ -e /proc/sys/kernel/sched_latency_ns ]; then
    echo "18000000" > /proc/sys/kernel/sched_latency_ns
    echo "18000000" > /proc/sys/kernel/sched_latency_ns;
	echo "Activited!"
fi

if [ -e /proc/sys/kernel/sched_wakeup_granularity_ns ]; then
    echo "3000000" > /proc/sys/kernel/sched_wakeup_granularity_ns
    echo "3000000" > /proc/sys/kernel/sched_wakeup_granularity_ns;
	echo "Activited!"
fi

if [ -e /proc/sys/net/core/somaxconn ]; then
    echo 1024 > /proc/sys/net/core/somaxconn;
    echo 1024 > /proc/sys/net/core/somaxconn
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_keepalive_time ]; then
    echo 1800 > /proc/sys/net/ipv4/tcp_keepalive_time;
    echo 1800 > /proc/sys/net/ipv4/tcp_keepalive_time
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_fin_timeout ]; then
    echo 1500 > /proc/sys/net/ipv4/tcp_fin_timeout;
    echo 1500 > /proc/sys/net/ipv4/tcp_fin_timeout
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_sack ]; then
    echo 0 > /proc/sys/net/ipv4/tcp_sack;
    echo 0 > /proc/sys/net/ipv4/tcp_sack
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_window_scaling ]; then
    echo 0 > /proc/sys/net/ipv4/tcp_window_scaling;
    echo 0 > /proc/sys/net/ipv4/tcp_window_scaling
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_timestamps ]; then
    echo 0 > /proc/sys/net/ipv4/tcp_timestamps;
    echo 0 > /proc/sys/net/ipv4/tcp_timestamps
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_tw_recycle ]; then
    echo 1 > /proc/sys/net/ipv4/tcp_tw_recycle
    echo 1 > /proc/sys/net/ipv4/tcp_tw_recycle;
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_dsack ]; then
    echo 1 > /proc/sys/net/ipv4/tcp_dsack
    echo 1 > /proc/sys/net/ipv4/tcp_dsack;
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_syn_retries ]; then
    echo 1 > /proc/sys/net/ipv4/tcp_syn_retries
    echo 1 > /proc/sys/net/ipv4/tcp_syn_retries;
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_tw_reuse ]; then
    echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse
    echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse;
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_synack_retries ]; then
    echo 1 > /proc/sys/net/ipv4/tcp_synack_retries
    echo 1 > /proc/sys/net/ipv4/tcp_synack_retries;
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_no_metrics_save ]; then
    echo 1 > /proc/sys/net/ipv4/tcp_no_metrics_save
    echo 1 > /proc/sys/net/ipv4/tcp_no_metrics_save;
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_keepalive_probes ]; then
    echo 5 > /proc/sys/net/ipv4/tcp_keepalive_probes
    echo 5 > /proc/sys/net/ipv4/tcp_keepalive_probes;
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_keepalive_intvl ]; then
    echo 20 > /proc/sys/net/ipv4/tcp_keepalive_intvl
    echo 20 > /proc/sys/net/ipv4/tcp_keepalive_intvl;
	echo "Activited!"
fi

if [ -e /proc/sys/net/ipv4/tcp_moderate_rcvbuf ]; then
    echo 1 > /proc/sys/net/ipv4/tcp_moderate_rcvbuf
    echo 1 > /proc/sys/net/ipv4/tcp_moderate_rcvbuf;
	echo "Activited!"
fi

if [ -e /sys/devices/virtual/bdi/0:18/read_ahead_kb ]; then
    echo 2048 > /sys/devices/virtual/bdi/0:18/read_ahead_kb
	echo 2048 > /sys/devices/virtual/bdi/0:18/read_ahead_kb;
	echo "Activited!"
fi
 
if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
    echo 2048 > /sys/devices/virtual/bdi/179:0/read_ahead_kb
	echo 2048 > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
	echo "Activited!"
fi
 
if [ -e /sys/devices/virtual/bdi/7:0/read_ahead_kb ]; then
    echo 2048 > /sys/devices/virtual/bdi/7:0/read_ahead_kb
	echo 2048 > /sys/devices/virtual/bdi/7:0/read_ahead_kb;
	echo "Activited!"
fi
 
if [ -e /sys/devices/virtual/bdi/7:1/read_ahead_kb ]; then
    echo 2048 > /sys/devices/virtual/bdi/7:1/read_ahead_kb
	echo 2048 > /sys/devices/virtual/bdi/7:1/read_ahead_kb;
	echo "Activited!"
fi
 
if [ -e /sys/devices/virtual/bdi/7:2/read_ahead_kb ]; then
    echo 2048 > /sys/devices/virtual/bdi/7:2/read_ahead_kb
	echo 2048 > /sys/devices/virtual/bdi/7:2/read_ahead_kb;
	echo "Activited!"
fi
 
if [ -e /sys/devices/virtual/bdi/7:3/read_ahead_kb ]; then
    echo 2048 > /sys/devices/virtual/bdi/7:3/read_ahead_kb
	echo 2048 > /sys/devices/virtual/bdi/7:3/read_ahead_kb;
	echo "Activited!"
fi
 
if [ -e /sys/devices/virtual/bdi/7:4/read_ahead_kb ]; then
    echo 2048 > /sys/devices/virtual/bdi/7:4/read_ahead_kb
	echo 2048 > /sys/devices/virtual/bdi/7:4/read_ahead_kb;
	echo "Activited!"
fi
 
if [ -e /sys/devices/virtual/bdi/7:5/read_ahead_kb ]; then
    echo 2048 > /sys/devices/virtual/bdi/7:5/read_ahead_kb
	echo 2048 > /sys/devices/virtual/bdi/7:5/read_ahead_kb;
	echo "Activited!"
fi
 
if [ -e /sys/devices/virtual/bdi/7:6/read_ahead_kb ]; then
    echo 2048 > /sys/devices/virtual/bdi/7:6/read_ahead_kb
	echo 2048 > /sys/devices/virtual/bdi/7:6/read_ahead_kb;
	echo "Activited!"
fi
 
if [ -e /sys/devices/virtual/bdi/7:7/read_ahead_kb ]; then
    echo 2048 > /sys/devices/virtual/bdi/7:7/read_ahead_kb
	echo 2048 > /sys/devices/virtual/bdi/7:7/read_ahead_kb;
	echo "Activited!"
fi
 
if [ -e /sys/devices/virtual/bdi/179:8/read_ahead_kb ]; then
    echo 2048 > /sys/devices/virtual/bdi/7:7/read_ahead_kb
	echo 2048 > /sys/devices/virtual/bdi/7:7/read_ahead_kb;
	echo "Activited!"
fi
 
if [ -e /sys/devices/virtual/bdi/default/read_ahead_kb ]; then
    echo 2048 > /sys/devices/virtual/bdi/default/read_ahead_kb
	echo 2048 > /sys/devices/virtual/bdi/default/read_ahead_kb;
	echo "Activited!"
fi

if [ -e /sys/module/lowmemorykiller/parameters/minfree ]; then
    echo 1024,1280,1536,1792,3072,4096 > /sys/module/lowmemorykiller/parameters/minfree
	echo 1024,1280,1536,1792,3072,4096 > /sys/module/lowmemorykiller/parameters/minfree;
	echo "Activited!"
fi

if [ -e /sys/module/lowmemorykiller/parameters/adj ]; then
    echo 0,100,150,400,700,850 > /sys/module/lowmemorykiller/parameters/adj
	echo 0,100,150,400,700,850 > /sys/module/lowmemorykiller/parameters/adj;
	echo "Activited!"
fi

if [ -e /sys/module/lowmemorykiller/parameters/cost ]; then
    echo 64 > /sys/module/lowmemorykiller/parameters/cost
	echo 64 > /sys/module/lowmemorykiller/parameters/cost;
	echo "Activited!"
fi

if [ -e /proc/sys/fs/lease-break-time ]; then 
	echo 10 > /proc/sys/fs/lease-break-time
	echo 10 > /proc/sys/fs/lease-break-time;
	echo "Activited!"
fi

for i in $(ls /sys/bus/usb/devices/*/power/level);
do
	echo "auto" > $i;
done;

echo "02memory Complete! Next to 03prop"